#!/usr/bin/env python3

# QualvoSec
# QualvoSec is a minimalistic security patch management tool for unattended
# upgrades on Linux and BSD based systems that are obtaining their packages
# from a distribution based repository.
# Copyright (C) 2023 Florian Paul Azim Hoberg @gyptazy <gyptazy@gyptazy.ch>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

try:
    import apt
    api_apt = True
except ImportError as error:
        api_apt = False
import argparse
import configparser
import datetime
import logging
import os
try:
    import pkg
    api_pkg = True
except ImportError as error:
        api_pkg = False
try:
    import rpm
    api_rpm = True
except ImportError as error:
        api_rpm = False
import socket
import subprocess
import sys
import time
import threading
import urllib
try:
    import yaml
except ImportError as error:
        logging.critical('QualvoSec: Can not start QualvoSec. Missing Python module: yaml')
        sys.exit(2)
from urllib.request import urlretrieve
try:
    from http.server import HTTPServer, BaseHTTPRequestHandler
except ImportError as error:
    logging.critical('QualvoSec: Can not start monitoring endpoint. Missing Python module: http')
    sys.exit(2)


# Constants
__appname__ = "QualvoSec"
__version__ = "1.0.2"
__author__  = "Florian Paul Azim Hoberg <gyptazy@gyptazy.ch> @gyptazy"


## Classes
# Logging class
class SystemdHandler(logging.Handler):
    """ Class to handle logging options. """
    PREFIX = {
        logging.CRITICAL: "<2> " + __appname__ + ": ",
        logging.ERROR: "<3> " + __appname__ + ": ",
        logging.WARNING: "<4> " + __appname__ + ": ",
        logging.INFO: "<6> " + __appname__ + ": ",
        logging.DEBUG: "<7> " + __appname__ + ": ",
        logging.NOTSET: "<7 " + __appname__ + ": ",
    }

    def __init__(self, stream=sys.stdout):
        self.stream = stream
        logging.Handler.__init__(self)

    def emit(self, record):
        try:
            msg = self.PREFIX[record.levelno] + self.format(record) + "\n"
            self.stream.write(msg)
            self.stream.flush()
        except Exception:
            self.handleError(record)


# Monitoring class
class MonitoringHandler(BaseHTTPRequestHandler):
    """ Class to respond for monitoring requests on QualvoSec. """
    def do_GET(self):
        self.send_response(200)
        self.send_header('Content-type', 'text/html')
        self.send_header(__appname__, __version__)
        self.end_headers()

        if self.path == '/health':
            http_content = self._get_http_health()
            self.wfile.write(f'healthy: {http_content}'.encode('utf-8'))

        elif self.path == '/get_package_list':
            system_os_pkg_mgr = _get_system_os_pkg_mgr('api')

            # Create package list for Debian based systems
            if system_os_pkg_mgr == '/bin/apt':
                if api_apt:
                    http_content = self._get_package_list_debian()
                    self.wfile.write(f'{http_content}'.encode('utf-8'))
                else:
                    self.wfile.write(f'Error: Missing Python library "apt".'.encode('utf-8'))

            # Create package list for RedHat based systems
            elif system_os_pkg_mgr == '/bin/rpm':
                if api_rpm:
                    http_content = self._get_package_list_redhat()
                    self.wfile.write(f'{http_content}'.encode('utf-8'))
                else:
                    self.wfile.write(f'Error: Missing Python library "rpm".'.encode('utf-8'))

            # Create package list for FreeBSD systems
            elif system_os_pkg_mgr == '/bin/pkg':
                if api_pkg:
                    http_content = self._get_package_list_freebsd()
                    self.wfile.write(f'{http_content}'.encode('utf-8'))
                else:
                    self.wfile.write(f'Error: Missing Python library "pkg".'.encode('utf-8'))

            # Return error is we cannot support the OS and therefore are unable to obtain a pkg list.
            else:
                self.wfile.write(f'Error: No supported OS found to provide package list.'.encode('utf-8'))

        # Return error message on unknown endpoints.
        else:
            self.wfile.write(f'Error: Not a supported endpoint requested.'.encode('utf-8'))


    def _get_http_health(self):
        """ Evaluate QualvoSec's current health status. """
        health_status = True
        return health_status

    def _get_package_list_debian(self):
        """ Get the systems local package list on a Debian based system. """
        cache = apt.Cache()
        installed_packages = {}
        for pkg in cache:
            if cache[pkg].is_installed:
                installed_packages[pkg.name] = pkg.installed.version
        return installed_packages

    def _get_package_list_redhat(self):
        """ Get the systems local package list on a RedHat based system. """
        ts = rpm.TransactionSet()
        mi = ts.dbMatch()
        installed_packages = {}
        for h in mi:
            name = h['name']
            version = h['version']
            release = h['release']
            epoch = h['epoch']
            pkg_version = f"{epoch}:{version}-{release}"
            installed_packages[name] = pkg_version
        return installed_packages

    def _get_package_list_freebsd(self):
        """ Get the systems local package list on a FreeBSD system. """
        installed_packages = {}
        db = pkg.PkgDb()
        for pkg_name in db:
            pkg_info = db[pkg_name]
            installed_packages[pkg_name] = pkg_info.version
        return installed_packages


## Functions
def initialize_args():
    """ Initialize given arguments for QualvoSec. """
    argparser = argparse.ArgumentParser(description='QualvoSec')
    argparser.add_argument('-c', '--config', type=str, help='Path to config file.')
    return argparser.parse_args()


def initialize_config_path(app_args):
    """ Initialize path to config file. """
    config_path = app_args.config
    if app_args.config is None:
        # Try to fallback on distribution default path.
        config_path = '/etc/qualvosec/qualvosec.conf'
    return config_path


def initialize_config_options(config_path):
    """ Read configuration from given config file for QualvoSec. """
    try:
        config = configparser.ConfigParser()
        config.read(config_path)
        server = config['general']['server']
        monitoring = config['general'].get('monitoring', False)
        monitoring_port = config['general'].get('monitoring_port', 8037)
        monitoring_listener = config['general'].get('monitoring_listener', '127.0.0.1')
        log_level = config['general'].get('log_level', 'CRITICAL')
        log_handler = config['general'].get('log_handler', 'SystemdHandler()')
    except configparser.NoSectionError:
        logging.critical('Error parsing config file: Section not found.')
        sys.exit(2)
    except configparser.ParsingError:
        logging.critical('Error parsing config file: Impossible to parse file.')
        sys.exit(2)
    except KeyError:
        logging.critical('Error parsing config file: Key/Value not found.')
        sys.exit(2)
    return server, log_level, log_handler, monitoring, monitoring_port, monitoring_listener


def initialize_logger(log_level, log_handler):
    """ Initialize desired logging handler. """
    root_logger = logging.getLogger()
    root_logger.setLevel(log_level)
    root_logger.addHandler(SystemdHandler())
    logging.info(f'Info: Logger initialized.')


def initialize_monitoring():
    """ Initialize monitoring status endpoint. """
    logging.info(f'Info: Initializing monitoring endpoint on port tcp/{monitoring_port}.')
    httpd = HTTPServer((monitoring_listener, int(monitoring_port)), MonitoringHandler)
    httpd.serve_forever()


def fetch_qualvosec_manifest(server, qualvosec_manifest_path, system_fqdn):
    """ Fetch the QualvoSec manifest from the remote server. """
    # Customize urllib opener.
    opener = urllib.request.build_opener()
    opener.addheaders = [('User-agent', f'{__appname__} {__version__} {system_fqdn}')]

    # Grab the initial QualvoSec manifest file once.
    urllib.request.install_opener(opener)
    if qualvosec_manifest_path is None:
        logging.info(f'Info: Trying to fetch manifest from {server}.')
        try:
            return urlretrieve(f'{server}/patch.yaml')
        except urllib.error.URLError:
            logging.critical(f'Error while fetching the manifest from {server}.')
            sys.exit(2)
    # Validate the file age for caching. Cache it during the runtime
    # and update the content every 6 hours.
    else:
        manifest_file_age = _get_file_age_time(qualvosec_manifest_path[0])
        if int(manifest_file_age) > 360:
            logging.info(f'Info: Trying to fetch manifest from {server}.')
            try:
                return urlretrieve(f'{server}/patch.yaml')
            except urllib.error.URLError:
                logging.critical(f'Error while fetching the manifest from {server}.')
                sys.exit(2)
        else:
            logging.info(f'Info: Cached manifest from {server} used.')
            return qualvosec_manifest_path


def read_qualvosec_manifest(qualvosec_manifest_path):
    """ Read the QualvoSec patch manifest. """
    logging.info(f'Info: Reading manifest file from {qualvosec_manifest_path}')
    with open(qualvosec_manifest_path, 'r') as test:
        qualvosec_manifest = yaml.safe_load(test)
    return qualvosec_manifest


def get_system_fqdn():
    """ Get the system's local fqdn. """
    logging.info(f'Info: Getting system fqdn.')
    return socket.getfqdn()


def _get_file_age_time(file_name):
    """ Get the file age time of a given file. """
    logging.info(f'Info: Getting file age time.')
    return time.time() - os.path.getmtime(file_name)


def _get_time_information_now():
    """ Get the current local time information. """
    logging.info(f'Info: Getting current time information.')
    return datetime.datetime.now().weekday(), datetime.datetime.now().hour, datetime.datetime.now().minute


def _get_time_information_patch(system_fqdn, qualvosec_manifest):
    """ Get the time information from QualvoSec manifest. """
    logging.info(f'Info: Getting manifest time information.')
    return qualvosec_manifest[system_fqdn]['weekday'], qualvosec_manifest[system_fqdn]['hour'], qualvosec_manifest[system_fqdn]['minute']


def _get_system_os_pkg_mgr(system_fqdn):
    """ Get the system's operating system package manager. """
    system_os = None
    system_os_debian  = '/bin/apt'
    system_os_redhat  = '/bin/rpm'
    system_os_freebsd = '/usr/sbin/pkg'
    supported_system_os = [system_os_debian, system_os_redhat, system_os_freebsd]

    for supported_os in supported_system_os:
        if os.path.exists(supported_os):
            system_os = supported_os
    
    if system_os is None:
            logging.critical(f'Error: The Operating System for {system_fqdn} could not be evaluated.')
            sys.exit(2)

    logging.info(f'Info: The Operating System for {system_fqdn} got evaluated and will use {system_os} for security patching.')
    return system_os


def _validate_systems_patch_window(qualvosec_times, system_fqdn):
    """ Validate if the system is in the patch window. """
    execute_patching = True
    for time_now, time_patch in qualvosec_times.items():
        if time_now != time_patch:
            execute_patching = False

    if not execute_patching:
        logging.info(f'Info: The system {system_fqdn} has not yet reached the security patch window.')
    else:
        logging.info(f'Info: The system {system_fqdn} has reached the security patch window and will be patched.')
    return execute_patching


def _execute_patch_system(system_os_pkg_mgmr, system_fqdn, system_packages_whitelist, system_packages_blacklist):
    """ Execute patching the system. """
    if system_os_pkg_mgmr == '/bin/apt':
        logging.info(f'Info: Using apt-get for patching.')
        os.environ['DEBIAN_FRONTEND'] = 'noninteractive'

        # Hold packages back from being upgraded if requested.
        if system_packages_blacklist:
            _execute_package_blacklisting(system_os_pkg_mgmr, system_fqdn, system_packages_blacklist)

        # Upgrade only specific packages if requested or upgrade all available ones.
        if system_packages_whitelist:
            process = subprocess.Popen(['sudo', 'apt-get', '-y', 'install', system_packages_whitelist], stderr=subprocess.PIPE, stdout=subprocess.PIPE)
        else:
            process = subprocess.Popen(['sudo', 'apt-get', '-y', 'upgrade'], stderr=subprocess.PIPE, stdout=subprocess.PIPE)

    elif system_os_pkg_mgmr == '/bin/rpm':
        logging.info(f'Info: Using yum for patching.')
        process = subprocess.Popen(['sudo', 'yum', '-y', 'upgrade', system_packages_whitelist], stderr=subprocess.PIPE, stdout=subprocess.PIPE)

    elif system_os_pkg_mgmr == '/bin/pkg':
        logging.info(f'Info: Using pkg for patching.')
        process = subprocess.Popen(['sudo', 'pkg', 'upgrade', '-yq', system_packages_whitelist], stderr=subprocess.PIPE, stdout=subprocess.PIPE)

    process_output, process_error = process.communicate()
    exit_code = process.wait()

    if exit_code != 0:
        logging.critical(f'Error The system {system_fqdn} could not be patched.')
        logging.critical(f'Log: {process_error}')
        sys.exit(2)
    else:
        logging.critical(f'Info: The system {system_fqdn} got successfully patched.')
        logging.info(f'Log: {process_output}')


def _validate_system_reboot(system_fqdn, qualvosec_manifest):
    """ Validate if system should be rebooted after security patching by QualvoSec. """
    logging.info(f'Info: Validating for reboot of system {system_fqdn}.')
    if qualvosec_manifest[system_fqdn].get('reboot'):
        logging.info(f'Info: System {system_fqdn} will be rebooted.')
        return True
    else:
        logging.info(f'Info: System {system_fqdn} will not be rebooted.')
        return False


def _get_system_packages_whitelist(system_fqdn, qualvosec_manifest):
    """ Get a list of packages that should only be updated by QualvoSec. """
    logging.info(f'Info: Validating for specific packages to update on system {system_fqdn}.')
    packages = qualvosec_manifest[system_fqdn].get('packages_whitelist', False)

    # Check if (a) specific package(s) are defined.
    if packages:
        logging.info(f'Info: System {system_fqdn} will only update the the following packages: {" ".join(packages)}')
        return " ".join(packages)
    else:
        logging.info(f'Info: System {system_fqdn} will update all available packages.')
        return False


def _get_system_packages_blacklist(system_fqdn, qualvosec_manifest):
    """ Get a list of packages that should be excluded from being updated by QualvoSec. """
    logging.info(f'Info: Validating for specific packages to exclude from being updated on system {system_fqdn}.')
    packages = qualvosec_manifest[system_fqdn].get('packages_blacklist', False)

    # Check if (a) specific package(s) are defined.
    if packages:
        logging.info(f'Info: System {system_fqdn} will not upgrade the the following packages: {" ".join(packages)}')
        return " ".join(packages)
    else:
        logging.info(f'Info: No packages found to exclude from being upgraded.')
        return False


def _execute_reboot_system(system_fqdn):
    """ Reboot the system after security patching by QualvoSec. """
    process = subprocess.Popen(['sudo', 'reboot'], stderr=subprocess.PIPE, stdout=subprocess.PIPE)
    process_output, process_error = process.communicate()
    exit_code = process.wait()
    if exit_code != 0:
        logging.critical(f'Error The system {system_fqdn} could not be rebooted.')
        logging.critical(f'Log: {process_error}')
        sys.exit(2)
    else:
        logging.critical(f'Info: The system {system_fqdn} will be rebooted now.')
        logging.info(f'Log: {process_output}')


def _execute_package_blacklisting(system_os_pkg_mgmr, system_fqdn, system_packages_blacklist):
    """ Block packages from being upgraded in a distro specific way. """
    if system_os_pkg_mgmr == '/bin/apt':
        logging.info(f'Info: Using Debian specific way to hold packages back from being updated on system {system_fqdn}.')
        process = subprocess.Popen(['sudo', 'apt-mark', 'hold', system_packages_blacklist], stderr=subprocess.PIPE, stdout=subprocess.PIPE)

    elif system_os_pkg_mgmr == '/bin/rpm':
        logging.info(f'Info: Using RedHat specific way to hold packages back from being updated on system {system_fqdn}.')
        process = subprocess.Popen(['sudo', 'yum', 'versionlock', 'add', system_packages_blacklist], stderr=subprocess.PIPE, stdout=subprocess.PIPE)

    elif system_os_pkg_mgmr == '/bin/pkg':
        logging.info(f'Info: Using FreeBSD specific way to hold packages back from being updated on system {system_fqdn}.')
        process = subprocess.Popen(['sudo', 'pkg', 'lock', system_packages_blacklist], stderr=subprocess.PIPE, stdout=subprocess.PIPE)

    process_output, process_error = process.communicate()
    exit_code = process.wait()

    if exit_code != 0:
        logging.critical(f'Error: System {system_fqdn} could not hold back the following packages from being update: {system_packages_blacklist}')
        logging.critical(f'Log: {process_error}')
        sys.exit(2)
    else:
        logging.critical(f'Info: System {system_fqdn} holds back the following packages from being update: {system_packages_blacklist}')
        logging.info(f'Log: {process_output}')



def patch_system(system_fqdn, qualvosec_manifest):
    """ Run the basic patch routine to integrate security fixes by QualvoSec. """
    # Validate that the system is present in the manifest.
    if not qualvosec_manifest.get(system_fqdn):
        logging.critical(f'Error: The system {system_fqdn} could not be found in the QualvoSec manifest.')
        sys.exit(2)

    # Validate that the system should be patched.
    if not qualvosec_manifest[system_fqdn].get('patch'):
        logging.warning(f'Warning: The system {system_fqdn} is not activated for security patching.')
        sys.exit(1)
    
    # Compare time slots for a matching time window.
    qualvosec_times = {}
    weekday_now,   hour_now,   minute_now   = _get_time_information_now()
    weekday_patch, hour_patch, minute_patch = _get_time_information_patch(system_fqdn, qualvosec_manifest)
    
    qualvosec_times[weekday_now] = weekday_patch
    qualvosec_times[hour_now]    = hour_patch
    qualvosec_times[minute_now]  = minute_patch

    # Check for patch window.
    execute_patching = _validate_systems_patch_window(qualvosec_times, system_fqdn)
    logging.info(f'Info: The system {system_fqdn} is in state execute_patching: {execute_patching}')

    # Check for specific packages to upgrade or to exclude from being upgraded.
    system_packages_whitelist = _get_system_packages_whitelist(system_fqdn, qualvosec_manifest)
    system_packages_blacklist = _get_system_packages_blacklist(system_fqdn, qualvosec_manifest)

    # Execute patching.
    if execute_patching:
        system_os_pkg_mgmr = _get_system_os_pkg_mgr(system_fqdn)
        _execute_patch_system(system_os_pkg_mgmr, system_fqdn, system_packages_whitelist, system_packages_blacklist)
        system_reboot_state = _validate_system_reboot(system_fqdn, qualvosec_manifest)
        if system_reboot_state:
            _execute_reboot_system(system_fqdn)


def main():
    """ Run QualvoSec - A minimalistic security patch management tool. """
    qualvosec_manifest_path = None
    global monitoring_port
    global monitoring_listener
    app_args = initialize_args()
    config_path = initialize_config_path(app_args)
    server, log_level, log_handler, monitoring, monitoring_port, monitoring_listener = initialize_config_options(config_path)
    initialize_logger(log_level, log_handler)
    if monitoring:
        threading.Thread(target=initialize_monitoring, name="monitoring").start()

    while True:
        system_fqdn = get_system_fqdn()
        qualvosec_manifest_path = fetch_qualvosec_manifest(server, qualvosec_manifest_path, system_fqdn)
        qualvosec_manifest = read_qualvosec_manifest(qualvosec_manifest_path[0])
        patch_system(system_fqdn, qualvosec_manifest)
        # Recheck after 50 seconds
        time.sleep(float(50))


if __name__ == '__main__':
    main()
